### ISSUE TITLE
setBfree does' t work well

### ISSUE THREAD

**Issue by Mickinator** [zynthian/zynthian-ui#355]
**Describe the bug**
set B free does not produce sound

**To Reproduce**
Layers/New Synth Layer
Engine/setBfree
MidiCh#1
Upper
Sine
AWSOP
→ no Sound

**Expected behavior**
sound is ok

from riban
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./zynthian_gui.py", line 1822, in cb_keybinding
    zyngui.callable_ui_action(action)
  File "./zynthian_gui.py", line 803, in callable_ui_action
    self.zynswitch_short(3)
  File "./zynthian_gui.py", line 1132, in zynswitch_short
    self.screens[self.active_screen].switch_select('S')
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 251, in switch_select
    self.click_listbox(None, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 247, in click_listbox
    self.select_action(self.index, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_bank.py", line 69, in select_action
    if self.zyngui.curlayer.set_bank(i):
  File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 150, in set_bank
    return self.engine.set_bank(self, self.bank_info)
  File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 301, in set_bank
    self.generate_config_file(midi_chans)
  File "/home/pi/zynthian-ui/zyngine/zynthian_engine_setbfree.py", line 215, in generate_config_file
    cfg_data = cfg_data.replace('#OSC.TUNING#', str(self.zyngui.fine_tuning_freq))
AttributeError: 'zynthian_gui' object has no attribute 'fine_tuning_freq'

**Screenshots**

**Setup:**
![grafik](https://user-images.githubusercontent.com/55761217/111032683-bd483780-840d-11eb-9a0e-d58fb7aefb20.png)

**Comment by jofemodo** [comment]
Ups! My fail! It should be solved now. Please update and test.
