### ISSUE TITLE
Touchscreen UI Button Freeze

### ISSUE THREAD

**Issue by zer0brain** [zynthian/zynthian-ui#494]
Hello i found a strange behavior on my DIY Zynthian, i don't no yet if it is only my machine but i can reproduce it quite easy.

1. Boot Zynthian
2. Load a Snapshot (004-Mistyc Arp + mod-UI on ch3 for me)
3. Enter Control View (ZynAddSubFX for me)
4. Push and [Layer] and [Select] Encoder Knob together couple of times, while always going back to control view if it changes.

If i do this at some Point the UI Touch buttons stop to work, but only buttons and title bar.
Preset, Next Chain, Learn, Page, Back-arrow, all stop working, but they are still pressed, touch animation works, just no Reaction.

But changing Knob Values and scrolling to the list on Touchscreen still works fine.
Its really only the buttons that don't do anything at this point.

At this state it was also not possible to reboot/shutdown it over web-ui.
Unplugging is the only way to get it back at this time.

I found this why wrongly trying to access X/Y Pad.

Raspberry Pi 4 Model B Rev 1.2
Audio: [Steinberg UR22 MKII!]
Display: [Pi 7 Touchscreen Display 800x480]
Wiring: [MCP23017_EXTRA]
I2C: [MCP23017@0x20, ADS1115@0x48]
Profile: [v4_stage]

zyncoder: stable (c452d2b)
zynthian-ui: [stable (f19f78c)])
zynthian-sys: [stable (7a69951)]
zynthian-data: [stable (5a40e04)]
zynthian-webconf: [stable (7e74565)]

#UI Stop working 1

Mar 11 09:16:38 zynthian startx[461]: self.zynswitches()
Mar 11 09:16:38 zynthian startx[461]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1829, in zynswitches
Mar 11 09:16:38 zynthian startx[461]: self.zynswitch_timing(i, dtus)
Mar 11 09:16:38 zynthian startx[461]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1842, in zynswitch_timing
Mar 11 09:16:38 zynthian startx[461]: if not self.zynswitch_double(i):
Mar 11 09:16:38 zynthian startx[461]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1982, in zynswitch_double
Mar 11 09:16:38 zynthian startx[461]: self.screens['control'].set_xyselect_mode(i, j)
Mar 11 09:16:38 zynthian startx[461]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 357, in set_xyselect_mode
Mar 11 09:16:38 zynthian startx[461]: self.x_zctrl = self.zgui_controllers[xctrl_i].zctrl
Mar 11 09:16:38 zynthian startx[461]: IndexError: list index out of range 

#UI Stop Working 2

Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui.zynswitch_double: Double Switch 4+2
Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui_control.set_controller_screen: SET CONTROLLER SCREEN Ctrls#1
Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui_controller.config: ZCTRL 'Filter Channel': 6 (0 -> 16), ['Any', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui_controller.config: ZCTRL 'Scale': 2 (0 -> 11), ['C Major', 'C#/Db Major', 'D Major', 'D#/Eb Major', 'E Major', 'F Major', 'F#/Gb Major', 'G Major', 'G#/Ab Major', 'A Major', 'A#/Bb Major', 'B Major'], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui_controller.config: ZCTRL 'Hold Chord': 1 (0 -> 1), ['Off', 'On'], [0, 1]
Mar 11 09:34:18 zynthian startx[1713]: DEBUG:zynthian_gui_controller.config: ZCTRL 'prime': 1 (0 -> 1), ['off', 'on'], [0, 1]
Mar 11 09:34:18 zynthian startx[1713]: ERROR:zynthian_gui.zynswitch_read: list index out of range
Mar 11 09:34:18 zynthian startx[1713]: Traceback (most recent call last):
Mar 11 09:34:18 zynthian startx[1713]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 2043, in zynswitch_read
Mar 11 09:34:18 zynthian startx[1713]: self.zynswitches()
Mar 11 09:34:18 zynthian startx[1713]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1829, in zynswitches
Mar 11 09:34:18 zynthian startx[1713]: self.zynswitch_timing(i, dtus)
Mar 11 09:34:18 zynthian startx[1713]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1842, in zynswitch_timing
Mar 11 09:34:18 zynthian startx[1713]: if not self.zynswitch_double(i):
Mar 11 09:34:18 zynthian startx[1713]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1982, in zynswitch_double
Mar 11 09:34:18 zynthian startx[1713]: self.screens['control'].set_xyselect_mode(i, j)
Mar 11 09:34:18 zynthian startx[1713]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 357, in set_xyselect_mode
Mar 11 09:34:18 zynthian startx[1713]: self.x_zctrl = self.zgui_controllers[xctrl_i].zctrl
Mar 11 09:34:18 zynthian startx[1713]: IndexError: list index out of range 

#UI Stop Working 3

Mar 11 09:44:24 zynthian startx[1712]: ERROR:zynthian_gui.zynswitch_read: list index out of range
Mar 11 09:44:24 zynthian startx[1712]: Traceback (most recent call last):
Mar 11 09:44:24 zynthian startx[1712]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 2043, in zynswitch_read
Mar 11 09:44:24 zynthian startx[1712]: self.zynswitches()
Mar 11 09:44:24 zynthian startx[1712]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1829, in zynswitches
Mar 11 09:44:24 zynthian startx[1712]: self.zynswitch_timing(i, dtus)
Mar 11 09:44:24 zynthian startx[1712]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1842, in zynswitch_timing
Mar 11 09:44:24 zynthian startx[1712]: if not self.zynswitch_double(i):
Mar 11 09:44:24 zynthian startx[1712]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1982, in zynswitch_double
Mar 11 09:44:24 zynthian startx[1712]: self.screens['control'].set_xyselect_mode(i, j)
Mar 11 09:44:24 zynthian startx[1712]: File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 357, in set_xyselect_mode
Mar 11 09:44:24 zynthian startx[1712]: self.x_zctrl = self.zgui_controllers[xctrl_i].zctrl
Mar 11 09:44:24 zynthian startx[1712]: IndexError: list index out of range

**Comment by zer0brain** [comment]
Was not aware of the Issue Tracking Repo, will Close this here and open it there.

**Comment by zer0brain** [comment]
moved: https://github.com/zynthian/zynthian-issue-tracking/issues/983
